site_name: gd-edit docs
pages:
  - Getting Started: index.md
  - Commands: commands.md
  - FAQ: faq.md

markdown_extensions:
  - admonition

theme: 'cinder'

extra_css: [css/extra.css]

google_analytics: ['UA-102949209-1', 'auto']
