site_name: gd-edit docs
pages:
  - Getting Started: index.md
  - Commands: commands.md
  - FAQ: faq.md

markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.gemoji

theme: material
extra_css: [css/extra.css]

google_analytics: ['UA-102949209-1', 'auto']
